import Head from 'next/head'
import { Inter } from 'next/font/google'
import VideoPlayer from 'Src/components/player'

const inter = Inter({ subsets: ['latin'] })

export default function Root() {
  return (
    <>
      <Head>
        <title>insider.video</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        Пустой шаблон c плеером
        <VideoPlayer />
      </main>
    </>
  )
}
